### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by tbille**
# Summary

- Add login limited to Canonical org in front of guides
- Update to use discourse.canonical.com guildes instead
- Add K8s configurations to get secrets for discourse docs

# QA

- `dotrun`
- http://0.0.0.0:8104/guides
- Make sure those pages are only accessible if you are logged in
- Make sure all other pages are accessible if you are NOT logged in

### CODE REVIEW

**Comment by sowasred2012** [comment]
@tbille I was able to view the other pages successfully, and I was prompted to log in for /guides, but after being returned from SSL, I saw this error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
StopIteration: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/scott/Projects/webteam.canonical.com/.venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/scott/Projects/webteam.canonical.com/.venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/scott/Projects/webteam.canonical.com/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/scott/Projects/webteam.canonical.com/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/scott/Projects/webteam.canonical.com/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/scott/Projects/webteam.canonical.com/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/scott/Projects/webteam.canonical.com/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/scott/Projects/webteam.canonical.com/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/scott/Projects/webteam.canonical.com/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/scott/Projects/webteam.canonical.com/.venv/lib/python3.8/site-packages/canonicalwebteam/discourse/app.py", line 156, in document_view
    self.parser.parse()
  File "/home/scott/Projects/webteam.canonical.com/.venv/lib/python3.8/site-packages/canonicalwebteam/discourse/parsers/docs.py", line 51, in parse
    self.index_topic = self.api.get_topic(self.index_topic_id)
  File "/home/scott/Projects/webteam.canonical.com/.venv/lib/python3.8/site-packages/canonicalwebteam/discourse/models.py", line 40, in get_topic
    return response.json()
  File "/snap/dotrun/58/lib/python3.8/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

**Comment by cristinadresch** [comment]
@tbille did you see this?

**Comment by tbille** [comment]
@sowasred2012 sorry for the delayed answer. You need credentials. I will MP them to you so you can test it out :smile:

**Review by sowasred2012 — APPROVED** [review]
LGTM!

**Pull request merged**
