### PR TITLE
Add basic Masterclasses view to the site

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Add basic Masterclasses view to the site

## QA
- Go to the demo
- Click the Masterclasses link
- View all the previous masterclasses

### CODE REVIEW

**Comment by anthonydillon** [comment]
@carkod finally got this the checks to pass

**Comment by carkod** [comment]
https://webteam-canonical-com-105.demos.haus/guides

**Comment by anthonydillon** [comment]
> https://webteam-canonical-com-105.demos.haus/

Huh?

**Review by carkod — APPROVED** [review]
LGTM

**Comment by anthonydillon** [comment]
Done

**Pull request merged**
